# Generated by Django 3.2.6 on 2021-08-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'permissions': (('can_view_new_ads', 'Can view new ads'),)},
        ),
    ]
