# Generated by Django 3.2.6 on 2021-08-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_advert_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'permissions': (('can_view_new_ads', 'Can view new ads'), ('can_view_rejected_ads', 'Can view rejected ads'))},
        ),
    ]
